CREATE TABLE ADDRESS (
    ADDRESS_ID INT AUTO_INCREMENT PRIMARY KEY,
    STREET1 VARCHAR(250) NOT NULL,
    STREET2 VARCHAR(250),
    STATE VARCHAR(250) NOT NULL,
    COUNTRY VARCHAR(250) NOT NULL,
    ZIP VARCHAR(250) NOT NULL
);

CREATE TABLE DOCUMENTS(
    FILE_ID INT AUTO_INCREMENT PRIMARY KEY,
    FILE_NAME VARCHAR(250) NOT NULL,
    FILE_TYPE VARCHAR(250) NOT NULL,
   DATA BLOB
);

CREATE TABLE USERS (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(250),
    FIRST_NAME VARCHAR(250),
    LAST_NAME VARCHAR(250),
    EMAIL_ID VARCHAR(250),

   ADDRESS_ID INT,
   FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID),

    FILE_ID INT,
    FOREIGN KEY (FILE_ID) REFERENCES DOCUMENTS(FILE_ID)

);
